version: '3'
services:
  app:
    container_name: app-server
    build: .
    ports:
      - 4000:4000
    external_links:
      - database
  database:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  